### ISSUE TITLE
u16 too small

### ISSUE THREAD

**Issue by Dushistov** [astraw/framed-serial#1]
I used your crate to transfer data via TCP/IP and bluetooth rfcomm,
and u16 in general should be enough, but it too close to limit.

So is it possible to make length type to be generic parameter, not hardcoded?

**Comment by astraw** [comment]
Right now the overhead of `FramedConnection` is 3 bytes per packet: 1 sentinel byte and 2 bytes indicating the size as little-endian u16. To make the size generic, one would have to ensure the sender and receiver were compiled with the same size type or to add another byte of overhead indicating the size of the length field. I don't really like either of those options.

A further, more practical and less theoretical, challenge is that [the byteorder crate doesn't have any writer functions generic for the numeric type](https://docs.rs/byteorder/1.0.0/byteorder/enum.LittleEndian.html).

I think a better solution would be to work on https://github.com/awelkie/cobs.rs/issues/5 . Then we wouldn't need to encode the packet length explicitly at all anymore.
